SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."set_short_id"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  truncated_id TEXT;
BEGIN
  -- Gerar um UUID truncado para 15 caracteres
  truncated_id := LEFT(NEW.id::TEXT, 15);

  -- Verificar se já existe um ID com o mesmo valor na tabela
  WHILE EXISTS (SELECT 1 FROM notes WHERE short_id = truncated_id) LOOP
    -- Gerar outro UUID truncado caso haja colisão
    truncated_id := LEFT(gen_random_uuid()::TEXT, 15);
  END LOOP;

  -- Definir o valor único no campo short_id
  NEW.short_id := truncated_id;

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."set_short_id"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."nametypes" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."nametypes" OWNER TO "postgres";


ALTER TABLE "public"."nametypes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."nametypes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notes" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "title" "text" NOT NULL,
    "content" "text" NOT NULL,
    "author" "uuid" NOT NULL,
    "is_public" boolean DEFAULT false,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "short_id" "text"
);


ALTER TABLE "public"."notes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."records" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "owner" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "name" "text" NOT NULL,
    "type" bigint NOT NULL,
    "status" bigint DEFAULT '1'::bigint NOT NULL,
    "target" "text" NOT NULL,
    "proxied" boolean DEFAULT false NOT NULL,
    "cloudflareId" "text"
);


ALTER TABLE "public"."records" OWNER TO "postgres";


ALTER TABLE "public"."records" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."record_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."secrets" (
    "id" bigint NOT NULL,
    "name" "text",
    "value" "text"
);


ALTER TABLE "public"."secrets" OWNER TO "postgres";


COMMENT ON TABLE "public"."secrets" IS 'store api keys and secrets';



ALTER TABLE "public"."secrets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."secrets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."status" (
    "id" bigint NOT NULL,
    "description" character varying NOT NULL
);


ALTER TABLE "public"."status" OWNER TO "postgres";


ALTER TABLE "public"."status" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."nametypes"
    ADD CONSTRAINT "nametypes_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."nametypes"
    ADD CONSTRAINT "nametypes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_short_id_key" UNIQUE ("short_id");



ALTER TABLE ONLY "public"."records"
    ADD CONSTRAINT "record_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."records"
    ADD CONSTRAINT "records_cloudflareId_key" UNIQUE ("cloudflareId");



ALTER TABLE ONLY "public"."secrets"
    ADD CONSTRAINT "secrets_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."secrets"
    ADD CONSTRAINT "secrets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."status"
    ADD CONSTRAINT "status_description_key" UNIQUE ("description");



ALTER TABLE ONLY "public"."status"
    ADD CONSTRAINT "status_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "generate_short_id" BEFORE INSERT ON "public"."notes" FOR EACH ROW EXECUTE FUNCTION "public"."set_short_id"();



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_author_fkey" FOREIGN KEY ("author") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."records"
    ADD CONSTRAINT "record_owner_fkey" FOREIGN KEY ("owner") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."records"
    ADD CONSTRAINT "record_status_fkey" FOREIGN KEY ("status") REFERENCES "public"."status"("id");



ALTER TABLE ONLY "public"."records"
    ADD CONSTRAINT "record_type_fkey" FOREIGN KEY ("type") REFERENCES "public"."nametypes"("id");



CREATE POLICY "Allow access to own notes" ON "public"."notes" FOR SELECT USING (("author" = "auth"."uid"()));



CREATE POLICY "Allow access to public notes" ON "public"."notes" FOR SELECT USING (("is_public" = true));



CREATE POLICY "Allow authenticated users to delete their records" ON "public"."records" FOR DELETE TO "authenticated" USING (("owner" = "auth"."uid"()));



CREATE POLICY "Allow delete own notes" ON "public"."notes" FOR DELETE USING (("author" = "auth"."uid"()));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."records" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Enable public to load record limit" ON "public"."secrets" FOR SELECT USING (("name" = 'limit'::"text"));



CREATE POLICY "Enable read for authenticated users only" ON "public"."records" FOR SELECT TO "authenticated" USING (("owner" = "auth"."uid"()));



CREATE POLICY "Enable update for users logged in" ON "public"."records" FOR UPDATE USING (("owner" = "auth"."uid"())) WITH CHECK (("owner" = "auth"."uid"()));



ALTER TABLE "public"."nametypes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."records" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."secrets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."status" ENABLE ROW LEVEL SECURITY;


CREATE PUBLICATION "realtime_messages_publication_" WITH (publish = 'insert, update, delete, truncate');


ALTER PUBLICATION "realtime_messages_publication_" OWNER TO "supabase_admin";




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."records";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON FUNCTION "public"."set_short_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_short_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_short_id"() TO "service_role";


















GRANT ALL ON TABLE "public"."nametypes" TO "anon";
GRANT ALL ON TABLE "public"."nametypes" TO "authenticated";
GRANT ALL ON TABLE "public"."nametypes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."nametypes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nametypes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nametypes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notes" TO "anon";
GRANT ALL ON TABLE "public"."notes" TO "authenticated";
GRANT ALL ON TABLE "public"."notes" TO "service_role";



GRANT ALL ON TABLE "public"."records" TO "anon";
GRANT ALL ON TABLE "public"."records" TO "authenticated";
GRANT ALL ON TABLE "public"."records" TO "service_role";



GRANT ALL ON SEQUENCE "public"."record_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."record_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."record_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."secrets" TO "anon";
GRANT ALL ON TABLE "public"."secrets" TO "authenticated";
GRANT ALL ON TABLE "public"."secrets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."secrets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."secrets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."secrets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."status" TO "anon";
GRANT ALL ON TABLE "public"."status" TO "authenticated";
GRANT ALL ON TABLE "public"."status" TO "service_role";



GRANT ALL ON SEQUENCE "public"."status_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."status_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."status_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;